"""Type stubs for the compiled Rust extension ``oxide_engine._core``.

Keep in sync with ``src/bindings/``.
"""

from typing import Any, Literal, Optional

__version__: str

class _DataLoaderModule:
    """The native ``_core.data_loader`` submodule."""

    @staticmethod
    def from_csv(path: str, symbol: Optional[str] = None, schema: Optional[dict[str, str]] = None) -> Ticker: ...

data_loader: _DataLoaderModule

SignalKind = Literal["long", "short", "flat", "scale_in", "scale_out"]

class Bar:
    def __init__(self, timestamp: int, open: float, high: float, low: float, close: float, volume: float) -> None: ...
    @property
    def timestamp(self) -> int:
        """Unix epoch milliseconds (UTC)."""
    @property
    def open(self) -> float: ...
    @property
    def high(self) -> float: ...
    @property
    def low(self) -> float: ...
    @property
    def close(self) -> float: ...
    @property
    def volume(self) -> float: ...

class Ticker:
    def __init__(self, symbol: str, bars: list[Bar]) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def bars(self) -> list[Bar]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Bar: ...

class Signal:
    @staticmethod
    def long(weight: float) -> Signal: ...
    @staticmethod
    def short(weight: float) -> Signal: ...
    @staticmethod
    def flat() -> Signal: ...
    @staticmethod
    def scale_in(weight: float) -> Signal: ...
    @staticmethod
    def scale_out(weight: float) -> Signal: ...
    @property
    def kind(self) -> SignalKind: ...
    @property
    def weight(self) -> Optional[float]: ...

class BacktestConfig:
    def __init__(
        self,
        starting_cash: float,
        commission: float = 0.0,
        slippage: float = 0.0,
        risk_free_rate: float = 0.0,
        periods_per_year: float = 252.0,
    ) -> None: ...
    @property
    def starting_cash(self) -> float: ...
    @property
    def commission(self) -> float: ...
    @property
    def slippage(self) -> float: ...
    @property
    def risk_free_rate(self) -> float: ...
    @property
    def periods_per_year(self) -> float: ...

class Trade:
    @property
    def symbol(self) -> str: ...
    @property
    def side(self) -> Literal["long", "short"]: ...
    @property
    def quantity(self) -> float: ...
    @property
    def entry_timestamp(self) -> int: ...
    @property
    def exit_timestamp(self) -> int: ...
    @property
    def entry_price(self) -> float: ...
    @property
    def exit_price(self) -> float: ...
    @property
    def pnl(self) -> float: ...
    @property
    def return_pct(self) -> float: ...
    @property
    def commission(self) -> float: ...
    @property
    def bars_held(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

class BacktestResult:
    @property
    def sharpe(self) -> float: ...
    @property
    def sortino(self) -> float: ...
    @property
    def calmar(self) -> float: ...
    @property
    def max_drawdown(self) -> float: ...
    @property
    def max_drawdown_duration(self) -> int: ...
    @property
    def total_return(self) -> float: ...
    @property
    def annualized_return(self) -> float: ...
    @property
    def annualized_volatility(self) -> float: ...
    @property
    def win_rate(self) -> float: ...
    @property
    def profit_factor(self) -> float: ...
    @property
    def avg_trade_pnl(self) -> float: ...
    @property
    def exposure(self) -> float: ...
    @property
    def num_trades(self) -> int: ...
    @property
    def starting_cash(self) -> float: ...
    @property
    def final_equity(self) -> float: ...
    @property
    def equity_curve(self) -> list[tuple[int, float]]: ...
    @property
    def drawdown_curve(self) -> list[tuple[int, float]]: ...
    @property
    def trades(self) -> list[Trade]: ...
    @property
    def config(self) -> BacktestConfig: ...
    def summary(self) -> dict[str, float]: ...

def run_backtest(strategy: Any, data: list[Ticker], config: BacktestConfig) -> BacktestResult: ...
